### ISSUE TITLE
RequestVerbLine always expects "HTTP/1.1" which is ignored anyway

### ISSUE THREAD

**Issue by tporadowski** [api1st/httprun#15]
Hi,

First of all - thanks for this handy tool! It seems that you are always expecting a line of type `RequestVerbLine` to end with `HTTP/1.1`, so when it is not there - parsing fails completely as none of the other groups are matched (verb, scheme, etc.). Yet, HTTP protocol version is ignored altogether, so I would suggest to make it optional.

Best Regards,
Tomasz

**Comment by api1st** [comment]
Thanks for your PR - This has been merged and so I am closing this issue.
