### ISSUE TITLE
Nuget package suggestion

### ISSUE THREAD

**Issue by frankhommers** [api1st/httprun#23]
Hi there,

I would like to "run" .http files from my own code. 
Would you consider making a nuget package that can do that?

Thanks!

Frank

**Comment by neiesc** [comment]
I'm using StartProcess to run httprun.exe in my xunit tests, it's a workaround

**Comment by frankhommers** [comment]
Yeah, that is a workaround. But I would like not to shell from my project. So not the workaround I am looking for.

**Comment by frankhommers** [comment]
I decided to serialize HttpRequestMessage and it's Content. That works for me.
Currently no need to run .http as is anymore.
